[package]
name = "project-maahes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx-rs = "0.4.1"
native-dialog = "0.6.3"
calamine = "0.18.0"